### ISSUE TITLE
collect: find a better way for XML-embedded help strings

### ISSUE THREAD

**Issue by fichtner** [opnsense/lang#1]
Currently problematic: excessive white space and embedded html

**Comment by fabianfrz** [comment]
@fichtner a sample in Ruby:
``` ruby
" Sample      help    text".gsub(/\s+/," ").strip
```

removing HTML tags may work as well by removing everything between '<' and '>'
``` ruby
'<p>Sample <span class="bold">help</span> text</p>'.gsub(/(<.*?>)/,"")
```

I hope that helps.

**Comment by fichtner** [comment]
@fabianfrz that would be one way to do it, but I'm afraid that those exact changes are required in the core.git in the code as well as the gettext extraction in lang.git. I'd rather favour a portable approach where the help strings are correct. I think there needs to be a bit of markup to support that, but not sure what...

**Comment by AdSchellevis** [comment]
@fichtner @fabianfrz the problem is that you cannot replace the text parts easily, because you don't know how it should replace the text back in another language. 
Maybe the easiest option is to add a special tag which we can easily feed to a translator, a bit like this:

```
<b><message>my bold text</message><b><br/>
<message>my normal text </message>
```

The advantage is that the parts are more explicit. Messages without <tags> could be handled as they are now or wrapped between the same tags.

**Comment by fichtner** [comment]
I don't think we have a good way to solve this without putting too much effort and this has been open forever.
