### ISSUE TITLE
System Information widget (translation)

### ISSUE THREAD

**Issue by f87** [opnsense/lang#56]
Good afternoon, I can not understand the translation of the widget "System Information":
1. The title of the widget " System Information "is missing in"POEditor".
2. The "CPU type" field has already been translated, but the widget is displayed incorrectly.
3. The "MBUF usage" field, similar.

![image](https://user-images.githubusercontent.com/62796525/109411240-b2bf8400-79b1-11eb-8e82-036846d04d46.png)
![image](https://user-images.githubusercontent.com/62796525/109411287-1053d080-79b2-11eb-9cd8-3f6ee724e022.png)
![image](https://user-images.githubusercontent.com/62796525/109411346-750f2b00-79b2-11eb-86d0-4d5ddde843fb.png)
![image](https://user-images.githubusercontent.com/62796525/109411381-c1f30180-79b2-11eb-8c15-079680996126.png)

**Comment by fichtner** [comment]
When there are changes to source text, even if just letter case changes the whole translation is invalidated. This is unfortunate but normal. We will never reach 100% coverage even if all translations are done because the time it takes to translate thousands of strings is longer than the time it takes to change one source string which could also happen for changing the text to be more current when previously it wasn’t.


Cheers,
Franco
